### ISSUE TITLE
Markdown basics

### ISSUE THREAD

**Issue by maptastik** [maptimelex/odysseyjs#2]
Just need a little reference for the key Markdown formatting used in OdysseyJS. We can still have a link to [daringfireball](http://daringfireball.net/projects/markdown/) or whatever, but it might be nice to have some of that basic Markdown syntax right there in the REAME

**Comment by insistondoubt** [comment]
Okay, pending any changes you want to make, I think this is okay now.

**Comment by maptastik** [comment]
Good stuff!
