### ISSUE TITLE
Pull together a few tile basemap URLs

### ISSUE THREAD

**Issue by maptastik** [maptimelex/odysseyjs#7]

**Comment by insistondoubt** [comment]
Added.

**Comment by maptastik** [comment]
YAY.

**Comment by insistondoubt** [comment]
That's what you were looking for I take it? More or less at least?

**Comment by maptastik** [comment]
Yeah. I might add a couple other sources, but if I don't what you added is more than enough. That's a great resource I'd forgotten about
